# Save as .codeclimate.yml (note leading .) in project root directory
  
languages:
  JavaScript: true
exclude_paths:
  - "build"
  - "external"
  - "bower_components"
  - "node_modules"



# languages:
#   JavaScript: true
# # exclude_paths:
# # - "foo/bar.rb"

# ratings:
#   paths:
#   - "app/**"
#   - "lib/**"
#   - Gemfile.lock
